name: shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: string
       run: echo " hello vamsi-devops16"
     - name: multiline script
       run: |
         node -v
         npn -v
    
